### ISSUE TITLE
r10k Post Hook

### ISSUE THREAD

**Issue by danjng** [jlcox1970/puppet-gitolite#3]
So, my understanding is that r10k needs to run as root, but the 'git' user that is created is not added to the sudoers file. Therefore, when committing and pushing to the git repository, even though the check-in succeeds, r10k is never kicked off and modules are not updated.

What's the best approach here? I'm thinking that we could add the saz/sudo Puppet Module as a dependency and add a few lines to manage git in the sudoers file?

I'm no expert by any means, and I'm sure this is somehow not secure. Maybe there's a way to manage the 'git' user entry in the sudoers file to only allow the r10k command?

Any input is welcome! Thanks!

**Comment by jlcox1970** [comment]
Currently on the servers where I am running this I am using the sudo to access to r10k command.
Not sure as to the security implications of this.
I think however that the use of the sudo module would be a good idea at this time

**Comment by jlcox1970** [comment]
There are actually 2 things that are needed in the sudoers file for this to function correctly.
The first is the actual call to r10k and the second is to disable the requirement for a tty session as git will not have one.

The following 2 lines take care of that

git ALL=(ALL) NOPASSWD:/usr/local/bin/r10k
Defaults:git !requiretty

After looking at the different modules for sudo on the forge I now leaning towards a using /etc/sudoers.d/gitolite as a destination and serving a template out of the module for this file

**Comment by danjng** [comment]
Ahhh! You beat me to the punch! :) 

I was doing research today and had the same findings. I had added entries already to my fork of your code, but your approach seems to be better in that the specific changes required for gitolite/r10k can be contained in its own file.

**Comment by jlcox1970** [comment]
Pushed update with the sudoers.d file.
Released as version 1.1.2 on the forge
